Testapi
monicagil/psl-workshop-api-testing-js pull request #2
Opened 2017-09-21 21:47 UTC by monicagil

2017-09-21 22:02 UTC, aperdomob requested changes

2017-09-21 22:02 UTC, aperdomob commented on test/MyFirstApiConsume.test.js
> +	it('Consume GET Service', () => {
mala indetanción en general de este metodo

2017-09-21 22:02 UTC, aperdomob commented on test/MyFirstApiConsume.test.js
> + });
mala indentación

2017-09-21 22:02 UTC, aperdomob commented on test/MyFirstApiConsume.test.js
> +   const body = {
mala indetanción del método

2017-09-21 22:02 UTC, aperdomob commented on test/MyFirstApiConsume.test.js
> +   const body = {
mala indetanción

2017-09-21 22:02 UTC, aperdomob commented on test/MyFirstApiConsume.test.js
> +
elimine las lineas en limpio

2017-09-21 22:02 UTC, aperdomob commented on test/MyFirstApiConsume.test.js
> +
elimine esta linea en limpio, solo deje una

2017-09-21 22:10 UTC, germandavid85 requested changes

2017-09-21 22:10 UTC, germandavid85 commented on test/MyFirstApiConsume.test.js
> +   const body = {
corregir indentación

2017-09-21 22:28 UTC, aperdomob commented
Quizas esta imagen te pueda ayudar facilmente a corregir la indentación en un archivo

![image](https://user-images.githubusercontent.com/17033942/30721565-49ba3a74-9ef2-11e7-801e-cec40bd1bfaa.png)

2017-09-21 23:09 UTC, jhenaoz requested changes

2017-09-21 23:09 UTC, jhenaoz commented on .gitignore
> +# End of https://www.gitignore.io/api/node
Add End Of File

2017-09-22 12:57 UTC, germandavid85 approved these changes

2017-09-22 13:37 UTC, aperdomob approved these changes

2017-09-22 13:38 UTC, jhenaoz approved these changes

2017-09-22 17:51 UTC, merged