Consumirpostpatch
monicagil/psl-workshop-api-testing-js pull request #35
Opened 2017-09-28 19:55 UTC by monicagil

2017-09-28 20:24 UTC, aperdomob requested changes
Monica estos PR me parecen extraños al incluir tantos archivos

2017-09-29 03:04 UTC, germandavid85 requested changes
solo debes adicionar `GithubApi.Issue.test.js` y los otros archivos no se deben eliminar

2017-09-29 03:04 UTC, germandavid85 commented on package.json
> +    "travis-cli": "^1.0.9"
esta dependencia no se necesita

2017-09-29 12:40 UTC, germandavid85 approved these changes

2017-09-29 13:08 UTC, aperdomob approved these changes

2017-09-29 13:32 UTC, merged