Reporte de Pruebas
monicagil/psl-workshop-api-testing-js pull request #6
Opened 2017-09-23 23:21 UTC by monicagil

![resultadopruebas](https://user-images.githubusercontent.com/32166699/30777921-fb1fbc18-a08b-11e7-9584-ba7904a59d1a.png)

2017-09-23 23:24 UTC, aperdomob requested changes

2017-09-23 23:24 UTC, aperdomob commented on package.json
> +}
agregar fin del linea

2017-09-23 23:31 UTC, aperdomob approved these changes

2017-09-24 16:22 UTC, germandavid85 approved these changes

2017-09-24 22:13 UTC, jhenaoz approved these changes

2017-09-25 11:34 UTC, merged