Autenticaciongithub
monicagil/psl-workshop-api-testing-js pull request #9
Opened 2017-09-25 22:44 UTC by monicagil

2017-09-25 22:57 UTC, aperdomob requested changes
falta el cambio en el travis

2017-09-26 12:34 UTC, jhenaoz requested changes
El CI esta fallando y hay unos cambios pendientes.

2017-09-26 12:34 UTC, jhenaoz commented on package.json
> +    "travis-cli": "^1.0.9"
esta libreria no es necesaria, removerla

2017-09-26 14:20 UTC, aperdomob requested changes

2017-09-26 14:20 UTC, aperdomob commented on package.json
> +  "name": "monicagil",
por que cambiaste el nombre, este estaba bien

2017-09-26 14:21 UTC, jhenaoz approved these changes

2017-09-26 15:14 UTC, jhenaoz commented on package.json
> +    "test": "test"
para que agregaste esto?

2017-09-26 15:17 UTC, aperdomob requested changes
resuelve los conflictos y asegurate que la integración continua pase

2017-09-26 20:55 UTC, aperdomob commented
Continua fallanado el PR, y resuelve los conflictos

2017-09-26 22:27 UTC, germandavid85 approved these changes

2017-09-26 23:08 UTC, aperdomob approved these changes

2017-09-27 11:31 UTC, merged